android {
    // Usamos la API 30 para que sea compatible con Android 11
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.bri3d.kwpandroidlogger"
        minSdkVersion 15
        targetSdkVersion 30 // Target Android 11
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            // Importante: En Gradle 2.1.0 se usa 'proguardFiles'
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    
    // Añadimos esto para evitar errores de compatibilidad de Java en el empaquetado
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
