// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        // En versiones viejas, se pone la URL completa en lugar de google()
        maven { url "https://maven.google.com" }
        mavenCentral()
        jcenter()
    }
    dependencies {
        // Bajamos un escalón a la 2.1.0 que es más compatible con Gradle 2.10
        classpath 'com.android.tools.build:gradle:2.1.0'
    }
}

allprojects {
    repositories {
        maven { url "https://maven.google.com" }
        mavenCentral()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
